apiVersion: v1
kind: Service
metadata:
  name: malwinder-nagp-dotnet-service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.nodePort }}
      port: 80
      name: http
  selector:
    app: malwinder-nagp-dotnet
